### ISSUE TITLE
Can you mark that Debatesum is query focused? 

### ISSUE THREAD

**Issue by Hellisotherpeople** [xcfcode/Summarization-Papers#3]
First of all, thank you for including my work here! 

DebateSum actually has "queries" for it's extractive summaries (which is the abstractive summary / argument made by the extractive summary). I emphasize this b cause I hope that future researchers in that very limited domain of query focused summarization use my dataset.

**Comment by xcfcode** [comment]
Done! Thx for this excellent dataset.
